### ISSUE TITLE
Can we use Dot net core Entity frame work for the DB having tables without PK

### ISSUE THREAD

**Issue by munish29sharma** [hherzl/Devshiva#1]
I heave to create service layer (Web API) in <b>Dot net Core</b> with <b>Entity-framework</b>.

Is it fine to use this architecture if there are lots of tables without Any primary key ?

I am new to this technology so please suggest.

**Comment by hherzl** [comment]
Hi.

If there aren't PKs defined in database, for this version of EF Core we need to define a key for each entity.

Hope it helps.

Regards
